apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: test-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: default-route-openshift-image-registry.apps.cluster-znwqn.dynamic.redhatworkshops.io/test-demo/my-app:latest
        ports:
        - containerPort: 8080
